name: Build và ký Android APK

on:
  push:
    branches:
      - main # Thay đổi nếu bạn muốn trigger workflow trên một branch khác
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Có thể dùng các runner khác như macos-latest hoặc windows-latest nếu cần

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true # Cần thiết nếu bạn có các submodule trong dự án

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Hoặc phiên bản Node.js bạn dùng

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: aarch64-linux-android, armv7-linux-androideabi # Thêm các target Android cần thiết

      - name: Install Rust dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libx11-xcb-dev libxcb-keysyms1-dev libdbus-1-dev

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # Phiên bản JDK yêu cầu bởi Tauri

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '33' # Hoặc phiên bản SDK bạn cần
          ndk-version: '25.2.8563309' # Phiên bản NDK. Hãy chắc chắn rằng phiên bản này tương thích với Tauri
          # Các components cần thiết. platforms;android-33 tương ứng với sdk-version 33
          with-command-line-tools: 'latest'
          cache-path: ${{ github.workspace }}/.android

      - name: Set up environment variables
        run: |
          echo "ANDROID_HOME=$HOME/android/sdk" >> $GITHUB_ENV
          echo "JAVA_HOME=$(/usr/libexec/java_home -v 17)" >> $GITHUB_ENV # Đặt JAVA_HOME
          echo "$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/build-tools/33.0.2" >> $GITHUB_PATH # Thay đổi 33.0.2 nếu bạn dùng phiên bản build-tools khác
          echo "CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=aarch64-linux-android-clang" >> $GITHUB_ENV
          echo "CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER=armv7-linux-androideabi-clang" >> $GITHUB_ENV

      - name: Change wrapper permissions
        run: chmod +x ./src-tauri/tauri

      - name: Install app dependencies
        run: npm install

      - name: Build app
        run: |
          npm run tauri android build

      - name: Sign APK
        if: success() # Chỉ thực hiện nếu build thành công
        uses: r0adkll/sign-android-release@v1 # Sử dụng action để ký APK
        with:
          releaseDirectory: ./src-tauri/gen/android/app/build/outputs/apk/universal/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }} # Base64 encoded keystore
          alias: ${{ secrets.KEY_ALIAS }} # Alias của key trong keystore
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }} # Mật khẩu của keystore
          keyPassword: ${{ secrets.KEY_PASSWORD }} # Mật khẩu của key (có thể giống keystore password)
          buildType: 'universal' # Build universal APK

      - name: Upload Signed APK
        if: success() # Chỉ upload nếu ký thành công
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: ./src-tauri/gen/android/app/build/outputs/apk/universal/release/*.apk # Đường dẫn đến APK đã ký
          retention-days: 5 # Giữ artifact trong 5 ngày